// ==UserScript==
// @name         Hugging Face 中文静态词库
// @namespace    https://github.com/izhadu/GreasyFork
// @version      2.0.0
// @description  Hugging Face 中文插件底层词库，作为 GreasyFork 外部依赖库使用。
// @author       izhadu
// @exclude      *
// ==/UserScript==

/**
 * @type {Map<string, string>}
 * @description 核心静态词库。
 * @why 采用 Map 数据结构进行寻址，确保词汇量激增时维持 O(1) 的检索时间复杂度，阻断原生对象遍历引起的性能劣化。
 */

window.HF_ZH_DICT = new Map([
    // ================= 核心导航与通用 =================
    ["Models", "模型"], ["Datasets", "数据集"], ["Spaces", "空间"], ["Docs", "文档"],
    ["Solutions", "解决方案"], ["Pricing", "定价"],
    ["Sign in", "登录"], ["Sign Up", "注册"], ["Search", "搜索"], ["Blog", "博客"], 
    ["Enterprise", "企业版"], ["Login", "登录"], ["Profile", "个人资料"], 
    ["Settings", "设置"], ["Logout", "退出登录"], ["Notifications", "通知"], ["Help", "帮助"],

    // ================= 侧边栏和 AI 任务 (专业术语对齐) =================
    ["Filters", "筛选器"], ["All", "全部"], ["Text", "文本"], ["Image", "图像"], ["Audio", "音频"],
    ["Video", "视频"], ["Multimodal", "多模态"], ["Table", "表格"], 
    ["Fill-Mask", "掩码填充"], ["Token Classification", "词元分类"],
    ["Text Generation", "文本生成"], ["Text2Text Generation", "文本对文本生成"], 
    ["Summarization", "文本摘要"], 
    ["Conversational", "对话"], ["Feature Extraction", "特征提取"], ["Translation", "翻译"], 
    ["Multiple Choice", "多项选择"], ["Text Classification", "文本分类"],
    ["Question Answering", "问答"], ["Sentence Similarity", "句子相似度"], ["Zero-Shot Classification", "零样本分类"],
    ["Audio-Text-to-Text", "语音转文本"],
    ["Image-Text-to-Text", "图文转文本"],
    ["Visual Question Answering", "视觉问答"], ["Document Question Answering", "文档问答"],
    ["Video-Text-to-Text", "视频转文本"], ["Visual Document Retrieval", "视觉文档检索"],
    ["Any-to-Any", "任意到任意"], ["Computer Vision", "计算机视觉"], ["Depth Estimation", "深度估计"],
    ["Image Classification", "图像分类"], ["Object Detection", "目标检测"], ["Image Segmentation", "图像分割"],
    ["Text-to-Image", "文生图"],
    ["Image-to-Text", "图生文"], ["Image-to-Image", "图生图"], ["Image-to-Video", "图生视频"], 
    ["Unconditional Image Generation", "无条件图像生成"],
    ["Video Classification", "视频分类"], ["Text-to-Video", "文生视频"], 
    ["Zero-Shot Image Classification", "零样本图像分类"], ["Mask Generation", "掩码生成"], 
    ["Zero-Shot Object Detection", "零样本目标检测"],
    ["Text-to-3D", "文生3D"], ["Image-to-3D", "图生3D"], ["Image Feature Extraction", "图像特征提取"],
    ["Keypoint Detection", "关键点检测"], ["Natural Language Processing", "自然语言处理"],
    ["Table Question Answering", "表格问答"], ["Text Ranking", "文本排序"], ["Text-to-Speech", "文本转语音"],
    ["Text-to-Audio", "文生音频"], ["Automatic Speech Recognition", "自动语音识别"],
    ["Audio-to-Audio", "音频到音频"], ["Audio Classification", "音频分类"], ["Voice Activity Detection", "语音活动检测"],
    ["Tabular", "表格数据"], ["Tabular Classification", "表格分类"], ["Tabular Regression", "表格回归"],
    ["Time Series Forecasting", "时间序列预测"], ["Reinforcement Learning", "强化学习"],
    ["Robotics", "机器人学"], ["Other", "其他"], ["Graph Machine Learning", "图机器学习"],

    // ================= 按钮、状态与操作 =================
    ["Load more", "加载更多"], ["Loading more...", "加载更多..."], ["Subscribe", "订阅"], 
    ["Download", "下载"], ["Upload", "上传"], ["Create", "创建"], ["Sign Out", "退出登录"], 
    ["Cancel", "取消"], ["Confirm", "确认"], ["Delete", "删除"], ["Edit", "编辑"], ["Save", "保存"], 
    ["Close", "关闭"], ["Back", "返回"], ["Next", "下一步"], ["Previous", "上一步"], 
    ["Continue", "继续"], ["Submit", "提交"], ["Copy", "复制"], ["Share", "分享"], 
    ["Like", "点赞"], ["like", "点赞"], ["Unlike", "取消点赞"], ["Follow", "关注"], 
    ["Unfollow", "取消关注"], ["View", "查看"], ["Hide", "隐藏"], ["Show more", "显示更多"], 
    ["Show less", "收起"],
    ["Expand", "展开"], ["Collapse", "收起"], ["Unknown", "未知"], ["Error", "错误"],

    // ================= 空间、设置、模型卡片详情 =================
    ["Model card", "模型卡片"], ["Files and versions", "文件与版本"], ["Community", "社区"],
    ["Training metrics", "训练指标"], ["Training logs", "训练日志"], ["Deploy", "部署"],
    ["Use in Transformers", "在 Transformers 中使用"], ["Hosted inference API", "托管推理 API"],
    ["Contributors", "贡献者"], ["Licenses", "许可证"], ["Likes", "点赞数"], ["Downloads", "下载量"],
    ["Tasks", "任务类型"], ["Languages", "语言类型"], ["Main", "主要"], ["Libraries", "模型库"],
    ["Duplicate this Space", "克隆此空间"],
    ["Embed this Space", "嵌入此空间"], ["App", "应用"], ["Files", "文件"], ["Sessions", "会话"], 
    ["Hardware", "硬件"], ["Storage", "存储"], ["Variables", "变量"], ["Logs", "日志"], 
    ["Space Hardware", "空间硬件配置"],
    ["Choose a hardware for your Space.", "为您的空间选择硬件。"],
    ["You'll be billed on a per minute basis.", "将按分钟计费。"],
    ["View usage in your billing settings.", "可在计费设置中查看使用情况。"],
    ["Sleep time settings", "休眠策略设置"],
    
    // 修复语境断裂：
    ["Sleep after", "连续无操作 "],
    ["of inactivity", " 后自动休眠"],
    
    ["Upgrade to a paid Hardware to set a custom sleep time.", "升级至付费硬件以自定义休眠时间。"],
    ["Pause Space", "暂停空间"], ["Building something cool as a side project?", "在构建有趣的业余项目？"],
    ["Apply for a community GPU grant.", "申请社区 GPU 赞助。"], ["Restart this Space", "重启此空间"],
    ["Restart Space", "重启空间"], ["Restart space", "重启空间"],
    ["Click this button to trigger a restart of your Space.", "点击此按钮触发空间重启。"],
    ["Factory rebuild", "出厂级重建"],
    ["Click this button to trigger a factory rebuild of your Space. This will invalidate Docker layer caches and rebuild your space from scratch, reinstalling all dependencies.", "使 Docker 缓存失效，并从零开始重新安装所有依赖。"],
    ["CPU basic", "基础 CPU"], ["CPU upgrade", "进阶 CPU"], ["Current", "当前运行"], ["Free", "免费"],
    ["Don't sleep", "永不休眠"], ["5 minutes", "5 分钟"], ["15 minutes", "15 分钟"], ["30 minutes", "30 分钟"],
    ["1 hour", "1 小时"], ["10 hours", "10 小时"], ["24 hours", "24 小时"],
    ["48 hours", "48 小时"], ["72 hours", "72 小时"], ["1 week", "1 周"],
    ["Dev mode", "开发者模式"], ["Enable dev mode", "启用开发者模式"], ["Enable Dev Mode", "启用开发者模式"],
    ["Dev mode allows you to remotely access your Space using SSH or VS Code.", "允许通过 SSH 或 VS Code 远程访问空间。"],
    ["Upgrade to PRO", "升级至 PRO 版"], ["Upgrade to", "升级至"], [" to enable Dev Mode.", " 以启用开发者模式。"],
    ["Change Space visibility", "更改可见性"], ["This Space is currently ", "当前状态："],
    ["public", "公开"], ["protected", "受保护"], ["private", "私有"],
    ["Public", "公开"], ["Protected", "受保护"], ["Private", "私有"], ["(PRO required)", "(需 PRO 订阅)"],
    [". Anyone on the internet can see this Space. Only you can commit.", "互联网上的任何人均可访问，但只有您可以提交更改。"],
    ["Storage Buckets", "存储桶 (Buckets)"],
    ["Mount HF Buckets into your Space for persistent storage. Buckets are shared storage volumes that persist across restarts.", "挂载 Hugging Face 存储桶以实现数据持久化（跨重启保留数据）。"],
    ["Mount a bucket", "挂载存储桶"], ["Storage Usage", "存储使用量"],
    ["Large File Storage Used", "大文件存储用量"], ["Storage limit", "存储上限"],
    ["Storage overview", "存储概览"], ["List Large Files", "列出大文件"],
    ["Variables and secrets", "环境变量与密钥"], ["No variables", "暂无变量"],
    ["Replace", "替换"], ["New variable", "新建变量"], ["New secret", "新建密钥"],
    ["Custom domain", "自定义域名"],
    ["Define a custom domain to host your Space. The custom domain must be a valid DNS name.", "绑定有效的 DNS 自定义域名以托管空间。"],
    [" to enable Custom Domain.", " 以启用自定义域名。"],
    ["Rename or transfer this Space", "重命名或转移空间"],
    ["All links to this Space will automatically redirect to the new location, including git operations. However, to avoid confusion, we recommend updating any existing local clones to point to the new repository URL. To do so, you can use the following command:", "所有链接（含 Git 操作）将自动重定向。但为了避免混淆，建议将本地克隆指向新仓库 URL："],
    ["New owner", "新所有者"], ["New name", "新名称"], ["I understand, move this Space", "我已知晓风险，转移空间"],
    ["Community contributions", "社区协作"], ["Discussions and Pull Requests", "讨论区与 PR(拉取请求)"],
    [" are currently ", " 当前处于 "], ["enabled", "开启"], ["disabled", "关闭"],
    ["for this Space. Members of the community", " 状态。社区成员 "], ["can", "可以"],
    ["propose changes to this repository.", " 提交代码更改。"],
    ["Default sorting in the Community Tab:", "社区动态默认排序："],
    ["Disable Discussions and PRs", "禁用讨论与 PR"], ["Webhooks", "网络钩子 (Webhooks)"],
    [" defined in ", " 个钩子定义于 "], ["user settings", "用户设置"],
    ["Analytics", "数据统计"], ["All time visits", "历史总访问"], ["Last month visits", "上月访问"],
    ["Last week visits", "上周访问"], ["Duplicates", "被克隆次数"], ["Xet storage", "Xet 存储"],
    ["Xet is HF Hub's new storage technology, offering up to 10x greater performance compared to Git LFS. Xet is currently", "HF Hub 的新一代存储技术，性能最高可达 Git LFS 的 10 倍。目前处于 "],
    ["Delete this Space", "删除此空间"], ["This action", "此操作 "], ["cannot", "不可"],
    ["be undone. This will permanently delete the", " 逆转。这将永久抹除 "],
    ["Space repository and all its files", " 空间代码库及其所有文件。"],
    ["Please type", "请输入 "], ["to confirm.", " 以确认删除。"],
    ["I understand, delete this Space", "我已知晓风险，确认删除"],
    ["Want to edit your Spaces's metadata? Head to the", "需编辑空间元数据？请直接修改 "],
    ["README.md and metadata UI", "README.md 文件"], ["instead.", "。"],

    // ================= 其它页面、表格与零散词汇 =================
    ["On this page", "本页大纲"], ["Table of contents", "目录"], ["Getting Started", "快速入门"],
    ["Tutorials", "教程"], ["Conceptual Guides", "概念指南"], ["How-to Guides", "操作指南"], ["API Documentation", "API 文档"],
    ["Collections", "收藏集"], ["Organizations", "组织机构"], ["Posts", "文章"], ["Daily Papers", "每日论文"],
    ["Learn", "学习"], ["Discord", "Discord"], ["Forum", "官方论坛"], ["Github", "GitHub"],
    ["Enterprise Hub", "企业中心"], ["Expert Support", "专家支持"], 
    ["Inference Endpoints", "推理端点"],
    ["Inbox", "收件箱"], ["New Model", "新建模型"], ["New Dataset", "新建数据集"], ["New Space", "新建空间"],
    ["New Collection", "新建收藏集"], ["Create organization", "创建组织"], ["Usage Quota", "资源配额"],
    ["Private Storage", "私有存储"], ["Public Storage", "公共存储"], ["Zero GPU", "零配置 GPU"],
    ["Inference Usage", "推理用量"], ["Subscribe to PRO", "订阅 PRO"], ["Access Tokens", "访问令牌"],
    ["Billing", "财务/账单"], ["Changelog", "更新日志"], ["AI & ML interests", "AI / ML 兴趣方向"],
    ["Recent Activity", "近期活动"], ["Account", "账户"], ["Authentication", "身份验证"],
    ["SSH and GPG Keys", "SSH / GPG 密钥"], ["Inference Providers", "推理提供商"],
    ["Papers", "学术论文"], ["Local Apps and Hardware", "本地应用与硬件"], ["Gated Repositories", "受限访问仓库"],
    ["Content Preferences", "内容偏好"], ["Connected Apps", "已授权应用"], ["Theme", "界面主题"],
    ["Discussions", "讨论区"], ["Pull requests", "拉取请求 (PR)"], ["Welcome to the community", "欢迎加入社区"],
    ["The community tab is the place to discuss and collaborate with the HF community!", "这里是与 Hugging Face 社区探讨与协作的专属阵地！"],
    ["New discussion", "发起讨论"], ["New pull request", "提交 PR"], ["Watch all activity", "关注所有动态"],
    ["View closed", "查看已关闭"], ["Sort:", "排序:"], ["Recently created", "最新创建"],
    ["Most reactions", "最多互动"], ["Trending", "近期热门"], ["Filter by title", "按标题过滤"],
    ["Filter by name", "按名称过滤"], ["Resources", "资源"], ["Search models, datasets, users...", "全局搜索 (模型、数据、用户...)"],
    ["No model card", "暂无模型卡片"], ["New: Create and edit this model card directly on the website!", "新功能：现在可直接在网页端创建和编辑模型卡片啦！"],
    ["Contribute a Model Card", "贡献模型卡片"], ["Adapters", "适配器 (Adapters)"], ["Finetunes", "微调版"],
    ["Merges", "合并版"], ["Quantizations", "量化版"],
    ["Models, datasets and Spaces", "模型、数据集与空间"], ["Discover, explore and share ML resources", "探索、发现并共享机器学习资源"],
    ["Top contributors", "核心贡献者"], ["Featured Spaces", "精选空间"], ["All Spaces", "所有空间"],
    ["Explore", "发现"], ["Browse models", "浏览模型"], ["Browse datasets", "浏览数据集"], ["Browse Spaces", "浏览空间"],
    ["Light theme", "浅色模式"], ["Light", "浅色"], ["Dark", "深色"], ["System", "跟随系统"], ["System theme", "系统默认"],
    ["Most likes", "最多点赞"], ["Most downloads", "最多下载"], ["Recently updated", "最近更新"],
    ["Task", "所属任务"], ["Library", "依赖库"], ["Dataset", "数据集"], ["Architecture", "模型架构"],
    ["Model name or keyword", "模型名称或关键字"], ["Search models", "搜索模型"], ["Parameters", "参数规模"],
    ["Most parameters", "最大参数量"], ["Least parameters", "最小参数量"], ["Full-text search", "全文检索"],
    ["Language", "语种"], ["Dataset name or keyword", "数据集名称或关键字"], ["Search datasets", "搜索数据集"],
    ["SDK", "开发包 (SDK)"], ["Space name or keyword", "空间名称或关键字"], ["Search Spaces", "搜索空间"],
    ["Hugging Face Documentation", "Hugging Face 官方文档"], ["Search the docs", "在文档中搜索"],
    ["Edit this page", "编辑此页"], ["Feedback", "问题反馈"], ["Documentation", "文档"],
    ["Model description", "模型简介"], ["Intended uses & limitations", "适用场景与局限性"], ["How to use", "使用说明"],
    ["Limitations and bias", "局限性与偏见"], ["Training data", "训练数据"], ["Training procedure", "训练流程"],
    ["Evaluation results", "评估结果"], ["Citation", "引用格式"], ["Model card authors", "卡片作者"],
    ["Model card contributors", "卡片贡献者"], ["Running on", "运行环境"], ["Last updated", "最后更新"],
    ["Created by", "创建者"], ["App files", "应用源码"], ["README.md", "README 文档"],
    ["Loading", "加载中..."], ["Success", "操作成功"], ["Warning", "警告"], ["Info", "提示"],
    ["No results found", "未找到匹配项"], ["Try adjusting your search or filter to find what you're looking for.", "请尝试调整搜索关键字或筛选条件。"],
    ["Something went wrong", "服务开小差了"], ["Please try again later", "请稍后重试"], ["Learn more", "了解更多"],
    ["Read documentation", "阅读文档"], ["Get started", "立即体验"], ["Create new", "新建"], ["Overview", "概览"],
    ["API Keys", "API 密钥"], ["Usage", "资源用量"], ["Members", "团队成员"], ["Support", "技术支持"],
    ["Privacy Policy", "隐私政策"], ["Terms of Service", "服务条款"], ["Cookie Policy", "Cookie 政策"],
    ["About", "关于我们"], ["Contact", "联系我们"], ["Guides", "开发指南"], ["API Reference", "API 参考手册"],
    ["Model Hub", "模型库"], ["Dataset Hub", "数据集中心"], ["Space Hub", "空间中心"], ["Inference API", "在线推理 API"],
    ["Widgets", "交互组件"], ["Training", "模型训练"], ["Education", "教育计划"], ["Research", "学术研究"], ["Partners", "合作伙伴"],
    ["Events", "社区活动"], ["Careers", "招贤纳士"], ["Security", "安全中心"], ["Status", "系统状态"], ["Open source", "开源生态"],
    ["Activity", "动态"], ["Commits", "代码提交 (Commits)"],
    ["Repositories", "代码库"], ["Buckets", "对象存储桶"], ["Repository", "代码库"], ["Type", "类型"], ["Jobs", "计算任务 (Jobs)"],
    ["PRO", "PRO版"], ["ENTERPRISE", "企业版"], ["Teams", "团队版"],
    ["Create repository", "创建代码库"], ["Add repository", "添加代码库"], ["Visibility", "访问权限"],
    ["of Total", "占比"], ["HuggingChat", "官方对话大模型"], ["Running", "运行中"], ["Buildpack", "构建环境 (Buildpack)"],
    ["Use environment", "使用环境"], ["Using", "当前使用"], ["View files", "浏览文件"], ["View repo", "查看仓库"], 
    ["View repo on GitHub", "在 GitHub 上查看"], ["Add a README.md", "添加 README.md"], ["Create a model card", "创建模型卡片"],
    ["Usage insights", "用量洞察"], ["Quickstart", "快速开始"], ["Run locally", "在本地运行"],
    ["Clone repository", "克隆代码库"], ["Add to collection", "加入收藏集"], ["Report this Space", "举报此空间"],
    ["Mute notifications", "免打扰模式"]
]);

/**
 * @description 动态正则匹配规则。
 * [修复] 原有的 (models?|datasets?|spaces?) 匹配会导致英文原词被回显（如"5个models"），现已拆分修复。
 */
window.HF_ZH_REGEX = [
    [/updated/i, '更新于'], 
    [/about/i, '大约'],
    [/\b(\d+) days?\s+ago\b/i, '$1 天前'],
    [/\b(\d+) hours?\s+ago\b/i, '$1 小时前'],
    [/\b(\d+) minutes?\s+ago\b/i, '$1 分钟前'],
    [/\bJust now\b/i, '刚刚'],
    [/\b(\d+) downloads?\b/i, '$1 次下载'],
    [/\b(\d+) likes?\b/i, '$1 次赞'],
    [/\bView closed \(?(\d+)\)?/i, '查看已关闭 ($1)'],
    
    // 正则分类修复：直接翻译动态数字后的特定英文名词
    [/\b(\d+) models?\b/i, '$1 个模型'],
    [/\b(\d+) datasets?\b/i, '$1 个数据集'],
    [/\b(\d+) spaces?\b/i, '$1 个空间'],
    [/\b(\d+) commits?\b/i, '$1 次提交']
];